ARG SCAMP_version=v2.6.7
ARG SWARP_version=2.38.0
ARG Sextractor_version=2.25.0
ARG PSFEX_version=3.21.1

FROM ubuntu:18.04
 
LABEL maintainer="David Corre <david.corre.fr@gmail.com>"

ENV USR newuser

# Install updates to base image
RUN \
  apt-get update -y \
  && apt-get install -y 

# Install requirements
RUN \
  apt-get install unzip wget curl git build-essential vim -y \ 
  && apt-get autoremove -y \
  && apt-get clean -y 

# switch ownership
# (all commands are root until a USER command changes that)
RUN useradd -ms /bin/bash ${USR}

USER ${USR}
# Set the working directory
WORKDIR /home/${USR}

#RUN addgroup --system --gid 998 anonymous \
#    && adduser --system --ingroup anonymous --uid 208 

# change ownership from root to newuser:
#RUN chown -R ${USR}:${USR}  /home/${USR}

# Create directory to link on volume with host machine
RUN \
   mkdir /home/${USR}/gmadet/

# Install python libraries through miniconda
#ENV PATH="/root/miniconda3/bin:${PATH}"
ENV PATH="/home/${USR}/miniconda3/bin:$PATH"
RUN \
   curl -m 7200 -OL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \ 
   && bash Miniconda3-latest-Linux-x86_64.sh -b \
   && rm -f Miniconda3-latest-Linux-x86_64.sh 

# Install python libraries
#RUN \
#   conda install python=3 numpy  

#RUN \ 
#   pip install hjson
WORKDIR /home/${USR}/gmadet

# define entrypoint which is the default executable at launch
ENTRYPOINT ["bash"] 
